services:
  - type: web
    name: finode-api
    env: node
    region: ohio
    plan: free
    buildCommand: npm install && npx prisma generate && npx prisma db push && npx tsx prisma/seed.ts
    startCommand: npx tsx src/index.ts
    envVars:
      - key: DATABASE_URL
        value: file:/tmp/finode-prod.db
      - key: JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
